### ISSUE TITLE
Multiple email API

### ISSUE THREAD

**Issue by detj** [NeverBounce/NeverBounceApi-NodeJS#1]
Is there any plan to add an API which takes an array of email strings And returns an array of result objects?

**Comment by mmollick** [comment]
We do have an API for handling bulk email verification, but we haven't added support for it in this wrapper yet and we likely won't be adding support for it until we release v4 of our API.

The nature of email verification makes it difficult to return the results for multiple emails in the response; it would almost always time out. So verifying emails in bulk requires a few steps; (1) make the initial startup request for the bulk job, (2) check the status of the bulk job, (3) then when finally finished retrieve the results.
You can read more about it here: https://neverbounce.com/help/api/verifying-a-list/

**Comment by detj** [comment]
Okay. That makes sense. I suppose it has to be managed on the consumer side then.
