### ISSUE TITLE
Documentation of Constructor mentions passing a string instead of an object

### ISSUE THREAD

**Issue by lukasnagl** [NeverBounce/NeverBounceApi-NodeJS#11]
[README.md](https://github.com/NeverBounce/NeverBounceApi-NodeJS/commit/318267c54e1d102e6f966166e3f389e54885e6b1#diff-04c6e90faac2675aa89e2176d2eec7d8R32) suggests initialising `NeverBounce` as:

```js
new NeverBounce('secret_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx');
```

The [implementation](https://github.com/NeverBounce/NeverBounceApi-NodeJS/blob/2bf288ced1ec33f089150c5151aad6bc9d4097ed/src/NeverBounce.js#L23) expects a configuration object with a key `apiKey`, though.

So it should likely be the following in `README.md`:

```js
new NeverBounce({ apiKey: 'secret_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' });
```

**Comment by mmollick** [comment]
I've updated the example in the readme.md. Thanks!
