### ISSUE TITLE
Add support for proxy config.

### ISSUE THREAD

**Issue by nricardo** [NeverBounce/NeverBounceApi-NodeJS#12]
There should be a way to set proxy config that relays all traffic calls to the NeverBounce service.

**Comment by mmollick** [comment]
Hi @nricardo, could you elaborate on this?

**Comment by nricardo** [comment]
Hi @mmollick,

We're using the library in our AWS servers, every call to the outside world needs to pass a given proxy on our infrastructure. If not no request are sent and an error is throwed, so no validation!

Since you're using the native NodeJS https library to do the actual HTTP requests, I think the solution is probably around something like this:

```
req.on('socket', function (socket) {
    socket.setTimeout(myTimeout);  
    socket.on('timeout', function() {
        req.abort();
    });
});
```

Please let me know if this is possible.
Thanks.

**Comment by mmollick** [comment]
That makes sense. I did some quick research and it looks like NodeJs' `http.agent` field is the preferred method of setting up HTTP proxies. (See https://github.com/stripe/stripe-node/pull/124)

Since our HttpsClient already passes through the `opts` object in our config, the method Stipe's NodeJs library uses should already work. 

Give this a try:
```
var ProxyAgent = require('https-proxy-agent');
var NeverBounce = require('neverbounce');

const client = new NeverBounce({
    apiKey: null,
    opts: {
        agent: new ProxyAgent({
            host: 'proxy',
            port: 8080
        })
    }
});
```

**Comment by nricardo** [comment]
Hi @mmollick ,

Sorry to reply just now, but only had the chance to test with your solution this morning.
Seems to work just fine 👍. Although I would like somebody else to confirm this in other environments.
Thanks for the support and awesome lib 👏.
