### ISSUE TITLE
Unhandled promise rejection for working deletions

### ISSUE THREAD

**Issue by lukasnagl** [NeverBounce/NeverBounceApi-NodeJS#16]
When calling the `neverbounce.jobs.delete(jobId)` route from our client, we’re getting unhandled promise rejections like the following:

```
(general_failure)
(node:61523) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 120): NeverBounce Error: We were unable to complete your request. The following information was supplied: Invalid job ID REDACTED
```

It seems like the **promise rejection is uncleanly handled in the library itself**. The **deletion itself works as intended**, but is only reported to be erroneous.

A call to delete all lists where a specific e-mail address was used would be convenient to comply with  _Art. 17 GDPR_.

**Comment by mmollick** [comment]
The error message "Invalid job ID REDACTED" would have come from the API response itself. This library wouldn't have generated that message on its own. That sounds like a bug on the API end. Could you send an email to support@neverbounce.com with the Job ID(s) that you received this error with?

As for GDPR compliance, any requests for deletions under GDPR should be sent to privacy@neverbounce.com. I will bring up your suggestion to our DPO at our next team meeting.

**Comment by lukasnagl** [comment]
> Invalid job ID REDACTED

I manually substituted the production job ID for the string `REDACTED`. 

The approach we do is to first search for the jobs we want to delete, and then send a deletion request, so it sounds indeed like an API issue.

**Comment by mmollick** [comment]
If you could send the production Job ID that this occurred with to support@neverbounce.com I'd be happy to look into this on the backend.
