### ISSUE TITLE
Typescript Definitions

### ISSUE THREAD

**Issue by kelindar** [NeverBounce/NeverBounceApi-NodeJS#2]
Just a suggestion: would be nice to have some typescript definitions for the API.

**Comment by penfold** [comment]
Typedefs are really needed and have them uploaded to NPM @types or even better include them in this package: http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by penfold** [comment]
A starting point could be MS auto gen tool: https://github.com/Microsoft/dts-gen

**Comment by georgenov** [comment]
We added TS definitions. Please check it here https://www.npmjs.com/package/@types/neverbounce
